In [1]:
# ===============================
# IPL Feature Engineering
# ===============================

import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\LENOVO\Downloads\mywork\Ipl_Analysis\/data/ipl_cleaned.csv", low_memory=False)

In [3]:
match_df = df.groupby("match_id").agg({
    "ipl_season": "first",
    "batting_team": "first",
    "bowling_team": "first",
    "toss_winner": "first",
    "toss_decision": "first",
    "match_won_by": "first",
    "venue": "first"
}).reset_index()

match_df.shape

(1169, 8)

In [4]:
match_df = match_df.rename(columns={
    "batting_team": "team1",
    "bowling_team": "team2"
})

In [5]:
match_df["team1_win"] = np.where(
    match_df["match_won_by"] == match_df["team1"],
    1,
    0
)

In [6]:
match_df["team1_win"].value_counts(normalize=True)

team1_win
0    0.550898
1    0.449102
Name: proportion, dtype: float64

In [7]:
match_df["toss_winner_is_team1"] = np.where(
    match_df["toss_winner"] == match_df["team1"],
    1,
    0
)

In [8]:
match_df["team1_batted_first"] = np.where(
    match_df["team1"] == match_df["toss_winner"],
    np.where(match_df["toss_decision"] == "bat", 1, 0),
    np.where(match_df["toss_decision"] == "field", 1, 0)
)

In [9]:
match_df[[
    "team1",
    "team2",
    "toss_winner",
    "toss_decision",
    "toss_winner_is_team1",
    "team1_batted_first"
]].head()

,team1,team2,toss_winner,toss_decision,toss_winner_is_team1,team1_batted_first
0,Kolkata Knight Riders,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,0,1
1,Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,1,1
2,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,1,1
3,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,bat,1,1
4,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,bat,1,1

In [10]:
first_innings_score = df[df["innings"] == 1] \
    .groupby("match_id")["team_runs"].max()

match_df = match_df.merge(
    first_innings_score.rename("first_innings_score"),
    on="match_id",
    how="left"
)

In [11]:
first_innings_wickets = df[df["innings"] == 1] \
    .groupby("match_id")["team_wicket"].max()

match_df = match_df.merge(
    first_innings_wickets.rename("first_innings_wickets"),
    on="match_id",
    how="left"
)

In [12]:
target_runs = df[df["innings"] == 2] \
    .groupby("match_id")["runs_target"].max()

match_df = match_df.merge(
    target_runs.rename("target_runs"),
    on="match_id",
    how="left"
)

In [13]:
match_df[[
    "first_innings_score",
    "first_innings_wickets",
    "target_runs"
]].head()

   first_innings_score  first_innings_wickets  target_runs
0                  222                      3        223.0
1                  240                      5        241.0
2                  129                      8        130.0
3                  165                      6        166.0
4                  110                     10        111.0

In [14]:
match_df["required_run_rate"] = (
    match_df["target_runs"] / 20
)

In [15]:
match_df["is_high_score"] = np.where(
    match_df["first_innings_score"] >= 180,
    1,
    0
)

In [16]:
match_df["is_very_high_score"] = np.where(
    match_df["first_innings_score"] >= 190,
    1,
    0
)

In [17]:
match_df["all_out_flag"] = np.where(
    match_df["first_innings_wickets"] == 10,
    1,
    0
)

In [18]:
match_df[[
    "first_innings_score",
    "required_run_rate",
    "is_high_score",
    "is_very_high_score",
    "all_out_flag"
]].head()

,first_innings_score,required_run_rate,is_high_score,is_very_high_score,all_out_flag
0,222,11.15,1,1,0
1,240,12.05,1,1,0
2,129,6.50,0,0,0
3,165,8.30,0,0,0
4,110,5.55,0,0,1

In [19]:
# Total matches played per team
team_matches = pd.concat([
    match_df["team1"],
    match_df["team2"]
]).value_counts()

# Total wins per team
team_wins = match_df["match_won_by"].value_counts()

# Win rate
team_win_rate = (team_wins / team_matches).fillna(0)

team_win_rate.head()

Chennai Super Kings    0.563492
Deccan Chargers        0.386667
Delhi Capitals         0.441948
Gujarat Lions          0.433333
Gujarat Titans         0.616667
Name: count, dtype: float64

In [20]:
match_df["team1_win_rate"] = match_df["team1"].map(team_win_rate)
match_df["team2_win_rate"] = match_df["team2"].map(team_win_rate)

In [21]:
match_df["win_rate_diff"] = (
    match_df["team1_win_rate"] - match_df["team2_win_rate"]
)

In [22]:
match_df[[
    "team1",
    "team2",
    "team1_win_rate",
    "team2_win_rate",
    "win_rate_diff"
]].head()

,team1,team2,team1_win_rate,team2_win_rate,win_rate_diff
0,Kolkata Knight Riders,Royal Challengers Bengaluru,0.511364,0.488889,0.022475
1,Chennai Super Kings,Punjab Kings,0.563492,0.450758,0.112734
2,Rajasthan Royals,Delhi Capitals,0.485106,0.441948,0.043159
3,Mumbai Indians,Royal Challengers Bengaluru,0.545126,0.488889,0.056237
4,Deccan Chargers,Kolkata Knight Riders,0.386667,0.511364,-0.124697

In [23]:
match_df.head()

,match_id,ipl_season,team1,team2,toss_winner,toss_decision,match_won_by,venue,team1_win,toss_winner_is_team1,...,first_innings_score,first_innings_wickets,target_runs,required_run_rate,is_high_score,is_very_high_score,all_out_flag,team1_win_rate,team2_win_rate,win_rate_diff
0,335982,2008,Kolkata Knight Riders,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Kolkata Knight Riders,"M Chinnaswamy Stadium, Bengaluru",1,0,...,222,3,223.0,11.15,1,1,0,0.511364,0.488889,0.022475
1,335983,2008,Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,"Punjab Cricket Association IS Bindra Stadium, ...",1,1,...,240,5,241.0,12.05,1,1,0,0.563492,0.450758,0.112734
2,335984,2008,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,Delhi Capitals,"Arun Jaitley Stadium, Delhi",0,1,...,129,8,130.0,6.50,0,0,0,0.485106,0.441948,0.043159
3,335985,2008,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,bat,Royal Challengers Bengaluru,"Wankhede Stadium, Mumbai",0,1,...,165,6,166.0,8.30,0,0,0,0.545126,0.488889,0.056237
4,335986,2008,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,bat,Kolkata Knight Riders,"Eden Gardens, Kolkata",0,1,...,110,10,111.0,5.55,0,0,1,0.386667,0.511364,-0.124697

In [24]:
match_df["team_pair"] = match_df.apply(
    lambda row: tuple(sorted([row["team1"], row["team2"]])),
    axis=1
)

In [25]:
# Total matches between pairs
pair_matches = match_df.groupby("team_pair")["match_id"].count()

# Team1 wins per pair
pair_team1_wins = match_df[match_df["team1_win"] == 1] \
    .groupby("team_pair")["match_id"].count()

# Head-to-head win rate for Team1
pair_win_rate = (pair_team1_wins / pair_matches).fillna(0)

In [26]:
match_df["team1_h2h_win_rate"] = match_df["team_pair"].map(pair_win_rate)

In [27]:
match_df[[
    "team1",
    "team2",
    "team1_h2h_win_rate"
]].head()

                   team1                        team2  team1_h2h_win_rate
0  Kolkata Knight Riders  Royal Challengers Bengaluru            0.371429
1    Chennai Super Kings                 Punjab Kings            0.468750
2       Rajasthan Royals               Delhi Capitals            0.533333
3         Mumbai Indians  Royal Challengers Bengaluru            0.411765
4        Deccan Chargers        Kolkata Knight Riders            0.555556

In [58]:
match_df = df.groupby("match_id").agg({
    "ipl_season": "first",
    "batting_team": "first",
    "bowling_team": "first",
    "toss_winner": "first",
    "toss_decision": "first",
    "match_won_by": "first",
    "win_type": "first",
    "win_margin": "first",
    "venue": "first"
}).reset_index()

match_df = match_df.rename(columns={
    "batting_team": "team1",
    "bowling_team": "team2"
})

match_df.head()

,match_id,ipl_season,team1,team2,toss_winner,toss_decision,match_won_by,win_type,win_margin,venue
0,335982,2008,Kolkata Knight Riders,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Kolkata Knight Riders,runs,140.0,"M Chinnaswamy Stadium, Bengaluru"
1,335983,2008,Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,"Punjab Cricket Association IS Bindra Stadium, ..."
2,335984,2008,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,Delhi Capitals,wickets,9.0,"Arun Jaitley Stadium, Delhi"
3,335985,2008,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,bat,Royal Challengers Bengaluru,wickets,5.0,"Wankhede Stadium, Mumbai"
4,335986,2008,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,"Eden Gardens, Kolkata"

In [60]:
matches_table = match_df[[
    "match_id",
    "ipl_season",
    "team1",
    "team2",
    "toss_winner",
    "toss_decision",
    "match_won_by",
    "win_type",
    "win_margin",
    "venue"
]].copy()

In [62]:
matches_table.to_csv(
    r"C:\Users\LENOVO\Downloads\mywork\Ipl_Analysis\/data/ipl_matches_clean.csv",
    index=False
)

In [64]:
deliveries_table = df[[
    "match_id",
    "innings",
    "over",
    "ball",
    "batter",
    "bowler",
    "runs_batter",
    "runs_total",
    "bowler_wicket",
    "extra_type"
]].copy()

deliveries_table.head()

,match_id,innings,over,ball,batter,bowler,runs_batter,runs_total,bowler_wicket,extra_type
0,335982,1,0,1,SC Ganguly,P Kumar,0,1,0,legbyes
1,335982,1,0,2,BB McCullum,P Kumar,0,0,0,NaN
2,335982,1,0,3,BB McCullum,P Kumar,0,1,0,wides
3,335982,1,0,3,BB McCullum,P Kumar,0,0,0,NaN
4,335982,1,0,4,BB McCullum,P Kumar,0,0,0,NaN

In [74]:
deliveries_table.to_csv(
    r"C:\Users\LENOVO\Downloads\mywork\Ipl_Analysis\/data/ipl_deliveries_clean.csv",
    index=False
)

In [68]:
team_season_summary = df.groupby(
    ["ipl_season", "batting_team"]
).agg({
    "match_id": "nunique",
    "team_runs": "mean"
}).reset_index()

team_season_summary.rename(columns={
    "batting_team": "team",
    "match_id": "matches_played",
    "team_runs": "avg_score"
}, inplace=True)

team_season_summary.head()

   ipl_season                   team  matches_played  avg_score
0        2008    Chennai Super Kings              16  75.502134
1        2008        Deccan Chargers              14  73.699640
2        2008         Delhi Capitals              14  75.989011
3        2008  Kolkata Knight Riders              13  67.811818
4        2008         Mumbai Indians              14  72.619318

In [72]:
team_season_summary.to_csv(
    r"C:\Users\LENOVO\Downloads\mywork\Ipl_Analysis\/data/ipl_team_season_summary.csv",
    index=False
)

In [94]:


from sqlalchemy import create_engine
import urllib

password = urllib.parse.quote_plus("Nsri@283")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/ipl_analytics"
)
engine.connect()

In [96]:
matches_table.to_sql(
    name="matches",
    con=engine,
    if_exists="replace",
    index=False
)

1169

In [98]:
deliveries_table.to_sql(
    name="deliveries",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=10000
)

278205